---
name: sslproxy
# director_uuid: <director-uuid> # CHANGE
director_uuid: ignore # REMOVE

releases:
 - name: sslproxy
   version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small # CHANGE

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      #net_id: <net-id> # specify net-id when openstack/neutron is running multiple networks
      security_groups:
        - sslproxy # CHANGE: Security group with ports 22, 80 & 443 open

resource_pools:
  - name: common
    network: default
    size: 1
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.small # CHANGE

jobs:
  - name: sslproxy
    template:
      - sslproxy
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
          - <floating-ip> # CHANGE one IP per sslproxy job instance

properties:
  router:
    port: 80
    servers:
      - 0.router.default.cf.microbosh # CHANGE
